### ISSUE TITLE
Using symbols instead of Strings for labels

### ISSUE THREAD

**Issue by vdichev** [jonifreeman/sqltyped#13]
I have a commit right now which constructs records with symbols as keys instead of strings. This has advantages as some of the operations for e.g. converting to/from case classes use symbols instead of Strings. OTOH it seems that using symbols significantly degrades performance.

I was wondering whether you have had observations on Strings vs. symbols since you've chosen to use Strings and operations with symbols seem to have been available as of Shapeless 2.0 already.

If it's about performance vs. convenience, I'm also wondering on whether this should be somehow configurable. However it's currently not possible to combine different configurations like useInputTags, keys, jdbcOnly and being globally configurable might not be flexible enough. Perhaps it's worth it to expose these flags as a user might like to e.g. have a jdbcOnly, keys and symbols-as-keys settings.

**Comment by jonifreeman** [comment]
Yes, compilation performance was the only reason to use Strings if I recall. But perhaps the performance is in a better shape after changes made in https://github.com/milessabin/shapeless/issues/50 ? How badly performance suffers if symbols are always used?

**Comment by vdichev** [comment]
I'll have to do a bit more rigorous testing, but the couple of times I tried it was somewhere around 30-50% more, which is not too principled because I'll have to take into account the time it took before I introduced sqltyped. Also, I'm not sure it's linear, I hope at least they have fixed the quadratic factor into something more manageable.

**Comment by vdichev** [comment]
I'm not sure if it's worth it using Symbols just for the sake of conversion to case classes anyway since it's quite inconvenient for a couple of reasons. The types won't match if there are:

* Any extra columns that don't map to a field in the case class
* Even the ordering will make a difference
* Any conversions even widening ones like Int -> Long or String -> Option[String] will not work.

Manipulating the record is an option but then getting the ordering right is tricky and in the end it's better to just extract the fields manually.

**Comment by vdichev** [comment]
I've tried again compiling with symbols and with strings, this time ensuring that there are no other differences in both projects and it doesn't seem that there is a noticeable difference now.

With Strings without exiting sbt I get 112 seconds and after several "clean; compile" runs it stabilizes to 69. With Symbols I get 113 seconds the first cold run and then it drops down to 80 seconds after warming up the sbt JVM. This seems to imply that after a freshly started sbt, there's no significant difference in compilation times. I'm not sure what to make of the slight increase (~16%) in compilation time after warm-up, but not sure this is going to affect compile times of anything other than the already comparatively short times of incremental compiles.

For comparison, without sqltyped the project compiled in 92 seconds without prewarming and eventually dropped down to 41s.

**Comment by jonifreeman** [comment]
Sounds good!

**Comment by vdichev** [comment]
Added configuration annotation to use symbols if desired.
