### ISSUE TITLE
String interpolation with input parameters

### ISSUE THREAD

**Issue by vdichev** [jonifreeman/sqltyped#14]
Some of the benefits of using String interpolation for queries is that one doesn't have to track the number and positions of params making it easier to develop, refactor and maintain. sqltyped is already using interpolation for SQL fragments. It might be worth it to implement both. For instance both Slick and Anorm use `$` for parameter interpolation and `#$` for "string splicing".

Any arguments for/against?

**Comment by jonifreeman** [comment]
I don't see any other cons but then the interpolated String is no longer copy-pasteable SQL which can be directly fed to a database (or into some other tool). But I'm not against this feature as it is completely optional to use interpolation if it suits better.

A bit off topic but I had one experimental feature on a roadmap to try out. Related to query composition. As SQL itself does not compose very well I planned to try if bigger SQL statements could be composed from smaller pieces by providing a small set of combinators. Like `Compose.and` in the example below.

    // (String) => [{age::Int, name::String}]
    val q1 = sql("SELECT age, name FROM person WHERE name LIKE ?")

    // (Int) => [{name::String, salary::Int}]
    val q2 =  sql("SELECT name, salary FROM person WHERE age>?")

    // (String, Int) => [{age::Int, name::String, salary::Int}]
    // generated SQL: SELECT age, name, salary FROM person WHERE name LIKE ? AND age>? 
    Compose.and(q1, q2)

**Comment by vdichev** [comment]
For an unmaintained project your responses sure are fast :)

The composition is quite interesting, it looks like a hybrid between a type-safe query DSL and plain SQL. How does this work, I imagine through the parser combinators but I guess not with the JDBC fallback?

One thing that would seem like a bit of a drawback is that it seems you can only compose valid queries, which seems like a bit of duplication if you only want to add a small fragment to a long query. At any rate, you don't often see an approach like that- I haven't.

**Comment by jonifreeman** [comment]
Haha yes I've responded today perhaps faster than normally :)

I imagined to implement it so that the `sql` function here would return an AST of the statement. Then `and` combinator would merge these ASTs and then a new SQL could be generated from the merged AST. To be honest, I'm not sure how easy it would be to implement that and get merging and typing semantically correct, and as you said this approach has its drawbacks as it requires some duplication and boilerplate. This might be a novel idea (hence a strong indicator that it might suck too :) but it would allow some interesting compositions which would not be possible to do with simpler interpolations. Here's `join` example:

    // (String) => [{age::Int, name::String}]
    val q1 = sql("SELECT age, name FROM person WHERE name LIKE ?")

    // () => [{salary::Int}]
    val q2 = sql("SELECT salary FROM job")

    // (String) => [{age::Int, name::String, salary::Int}]
    // generated SQL: SELECT p.age, p.name, j.salary FROM person p JOIN job j ON p.id=j.person WHERE p.name LIKE ? 
    Compose.join(q1, q2, ("id", "person"))

Anyway, I never saw strong enough need for a complex feature like that. It is an interesting idea but could be unnecessarily complex to get right.

**Comment by vdichev** [comment]
SQL syntax has some specifics which make String interpolation a bit less useful: in INSERT statements, where one is usually using a bigger number of parameters and consequently more likely to mix it up, the parameters are not located next to the column names anyway: `INSERT INTO table (colname1, colname2, colname3, ...) VALUES (val1, val2, val3, ...)`.

Besides, it's more difficult to set different options (jdbcOnly, useInputTags, keys) here- granted, useInputTags might not be useful at all anyway, but still.

**Comment by vdichev** [comment]
OK, I've got 2 use cases for interpolation:

1. For queries- it's much more common to combine whole SQL fragments and create dynamic queries. Also, it's usually necessary to refer to the result type if you want to pass it to other methods. On the other hand, there are often not that many input parameters. For this case the existing String interpolation works well.

2. For updates and inserts- these more often than not have a simple structure and do not need to be constructed dynamically. However, there could be many input parameters, making it more important to match correctly the params to the placeholders in the query. Here interpolation as params is more useful. This means that the query must be defined in the scope of the variables that are used as interpolation arguments and as a result it's not always possible to refer to the return type of the query, but this is rarely needed for updates/inserts- I haven't found a use case where I need to pass the result of these to another function and it's not a Shapeless record anyway.

1 and 2 are practically impossible to get in the same interpolator anyway. Based on this, I've created another interpolator:

https://github.com/jonifreeman/sqltyped/compare/master...vdichev:master

If you think this makes sense and looks good, I can push it directly to the original repo here.

**Comment by jonifreeman** [comment]
Looks good to me! 

Yes the return values for updates/inserts are sometimes not used at all. There's basically two cases I did use in my own project, 1) to get updated row count (needed quite rarely) 2) to get the autogenerated key values when inserting new rows (quite common need).
