### ISSUE TITLE
Consider configuration options

### ISSUE THREAD

**Issue by vdichev** [jonifreeman/sqltyped#16]
Currently sqltyped has several macros, each serving to pass a separate boolean parameter to the implementation: sqlj passes "jdbcOnly", sqlt passes "useInputTags" and sqlk passes "keys". I'm also wondering whether it's useful to have an option of using symbols as keys (https://github.com/jonifreeman/sqltyped/issues/13) and interpolation as parameters (https://github.com/jonifreeman/sqltyped/issues/14). In this case each new boolean parameter means an exponential number of combinations, leading to either too many abbreviations, e.g. sqljkt, which seems crazy, or missed combinations, e.g. I can't currently have jdbcOnly with keys, which seems like a reasonable combination. I'm wondering which other options to pass configurations you've thought about:

* passing a configuration name from the type of the implicit value, which is already used in SqlMacro and not such a bad idea considering the limitations
* using the DbConfig object to pass essentially global configuration options- this is also probably a good option considering sqltyped is already getting values from the config
* Using macro annotations (http://docs.scala-lang.org/overviews/macros/annotations) as described here: http://stackoverflow.com/questions/25127140/how-can-parameters-settings-be-passed-to-a-scala-macro. This seems to be fairly flexible with the restriction that both sqltyped and the projects using it need to have macro paradise enabled.

Obviously sqltyped is using the first 2 options, have you looked at macro annotations and if yes, do you know of any show-stoppers for using it?

**Comment by jonifreeman** [comment]
I wasn't aware of that macro annotation trick explained in the linked stackoverflow post. It could provide a reasonable solution to parametrize various versions of 'sql' functions. I did acknowledge that using a set of named functions like 'sql', 'sqlk' etc. probably won't be a good long term solution though. Perhaps there could be a couple of those for common cases and then a lower level function which requires a macro annotation for parametrization?

**Comment by vdichev** [comment]
That's what I was thinking- the current sqlt, sqlk, sqlj should stay, if nothing else but for backward-compatibility. Macro annotations would add fine-grained control over the set of parameters per query. And it would be nice if there was a way to configure a global setting. Actually there is a trick I forgot to mention which uses a setting in a scope- defining an implicit EnableTagging. The other option is possibly using the DbConfig- it would define a profile of config settings globally. Or maybe all of these are useful? What do you think?

**Comment by jonifreeman** [comment]
Could it be that macro annotation stuff is all that is needed actually? Then "configuration" would simply be to define project specific named functions in project's top level `package.scala`. For instance

    def @config("enableTags", "jdbcOnly", "returnGeneratedKeys") sqlSelect(s: String) = macro SqlMacro.sqlImpl
    def @config("enableTags", "jdbcOnly") sqlInsert(s: String) = macro SqlMacro.sqlImpl
    ....

**Comment by vdichev** [comment]
Right, I was getting carried away thinking about using the existing options. Then implicit EnableTagging seems obsolete?

Actually I was thinking more like using a separate annotation than strings, but this is just a cosmetic detail:

```scala
@enableTags @jdbcOnly @returnGeneratedKeys def sqlSelect(s: String) = macro SqlMacro.sqlImpl
@enableTags @jdbcOnly def sqlInsert(s: String) = macro SqlMacro.sqlImpl
```

**Comment by jonifreeman** [comment]
Yes, implicit EnableTagging would be obsolete and can be removed. I like separate annotations better too!

**Comment by vdichev** [comment]
It seems like macro paradise isn't needed after all- these are just normal static annotations and not macro annotations with a macroTransform method.

**Comment by vdichev** [comment]
Even though there might be benefits to using implicits or config files, it seems annotations by and large cover the use cases.
